POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRvbWF0byIsImlkIjoiNWVjNWFjZTRmOTU5NjMzZjU4NzJkN2U3IiwiaWF0IjoxNTkwMTA0ODQ4fQ.kQlbgp4cJfE6SZGCpUg28vDFUNYv8XLOq3TeBqQuTCY

{
 "title": "With middleware",
 "author": "Tomato",
 "url": "www.tomato.com",
 "likes": 14,
 "userId": "5ec5ad25f05fdf52f8a730ee"
}